# my-spark-cluster-values.yaml
sparkMaster:
  replicas: 1
  resources:
    requests:
      memory: "256m"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "256m"

worker:
  replicas: 2
  resources:
    requests:
      memory: "1Gi"
      cpu: "512m"
    limits:
      memory: "2Gi"
      cpu: "512m"
